blog2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_app.urls')),
    # accepting all auth urls such as login, logout, register
    # the urls will by default go to registration/register.html and registration/login.html as templates
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('blog_members.urls')),
    path('djrichtextfield/', include('djrichtextfield.urls')),
]

handler404 = 'blog_app.views.handler404'

blog_app/urls.py
from django.urls import path, include
# from . import views
from .views import HomeView, PostDetailView, AddPostView, EditPostView, DeletePostView, AddCategoryView, FilterView, FilterAuthorView, LikeView, CommentView, DeleteCommentView, aboutView


urlpatterns = [
    # path('', views.home, name='home'),

    # class based url
    path('', HomeView.as_view(), name='home'),
    path('p/<int:pk>', PostDetailView.as_view(), name='detail'),
    path('create/', AddPostView.as_view(), name='add_post'),
    path('p/edit/<int:pk>', EditPostView.as_view(), name='edit_post'),
    path('p/<int:pk>/delete', DeletePostView.as_view(), name='delete_post'),
    path('add_category/', AddCategoryView.as_view(), name='add_category'),

    path('c/<str:cat>', FilterView, name='filter'),
    path('u/<str:id>', FilterAuthorView, name='filter_by'),

    path('like/int:<pk>', LikeView, name='post_like'),
    path('p/<int:pk>/comment/', CommentView, name="comment"),
    path('p/<int:pk>/comment/delete',
         DeleteCommentView.as_view(), name="del-comment"),

    path('about/', aboutView, name='about'),

]

blog_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from django.urls import reverse
from ckeditor.fields import RichTextField

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return f'Category : {self.name}'

    # return to home when new category is added
    def get_absolute_url(self):
        return reverse('home')


class Post(models.Model):
    title = models.CharField(max_length=125)
    # content = models.TextField()
    content = RichTextField(blank=False, null=False)
    date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # post categories
    category = models.CharField(max_length=35, default='uncategorized')

    # likes
    likes = models.ManyToManyField(User, related_name='blog_posts')

    # get number of likes for a post

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return f'Title : {self.title} || Author : {self.author.username}'

    # get absolute method for submission of new post from create post view
    # send submitted form where?
    def get_absolute_url(self):
        return reverse('home')

        # detail page of added post
        # return reverse('detail', args=[str(self.pk)])


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=100)
    body = models.TextField()
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'Comment by : {self.name} Comment : {self.body}'

blog_app/forms.py
from djrichtextfield.widgets import RichTextWidget
from django.forms import ValidationError
from django.contrib.auth.models import User
from django import forms
from .models import Post, Comment
from.models import Category

# if we want to hard code categories into select field we can just do so by passing in python list
# (choice name, choice value)
# choices = [('Programming', 'Programming'),
#            ('Gaming', 'Gaming'), ('Sports', 'Sports')]

# better way is to get categories from the Category model

choices = Category.objects.all().values_list('name', 'name')


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'content', 'category', 'author']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'title of your post'}),

            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'write something here . . .'}),

            'author': forms.TextInput(attrs={'class': 'form-control', 'id': 'authorbox', "type": "hidden", "value": ""}),

            'category': forms.Select(choices=choices, attrs={'class': 'form-control'})
        }


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ['name']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'enter any new category'}),
        }

    def clean_name(self):
        entered_cat = self.cleaned_data.get('name').capitalize()

        category = Category.objects.filter(name=entered_cat)

        if category:
            raise ValidationError("Category already exists!")
        else:
            return entered_cat.capitalize()


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['body']

        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'write your comment here . . .'}),
        }

blog_app/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect, Http404
from .models import Post, Category, Comment
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User
from .forms import PostForm, CategoryForm
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from .forms import CommentForm
from django_currentuser.middleware import (
    get_current_user, get_current_authenticated_user)
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.template import RequestContext


def handler404(request, exception):
    return render(request, 'blog_app/404.html')


class HomeView(ListView):                   # view to use
    model = Post                            # model to use
    template_name = 'blog_app/home.html'    # temp to use
    ordering = ['-date']
    paginate_by = 5

    # code to pass categories as context to the home view so they appear in nav bar
    # for class based views we need to define context this way
    def get_context_data(self, *args, **kwargs):
        menu_items = Category.objects.all().values
        context = super(HomeView, self).get_context_data(*args, **kwargs)
        context["menu"] = menu_items

        # print(context)
        return context

# detailed view of individual posts
# this view will automatically get the post with the pk that was passed with the url pattern


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog_app/detail.html'

    def get_context_data(self, *args, **kwargs):
        post = get_object_or_404(Post, id=self.kwargs.get('pk'))
        context = super(PostDetailView, self).get_context_data(
            *args, **kwargs)

        liked = False

        user_liked = post.likes.filter(id=self.request.user.id)

        if user_liked:
            liked = True

        context["liked"] = liked
        return context


class AddPostView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm       # use our form
    template_name = 'blog_app/add_post.html'
    success_message = "Post added successfully!"
    # put all fields from model on the page
    # fields = '__all__'


class EditPostView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'blog_app/update_post.html'
    success_message = "Post updated!"


class DeletePostView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'blog_app/delete_post.html'
    success_message = "Post deleted!"

    # redirect after a post is deleted
    def get_success_url(self):
        return reverse('home')

    # for success message in delete view we do this -->
    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        messages.success(self.request, self.success_message % obj.__dict__)
        return super(DeletePostView, self).delete(request, *args, **kwargs)


class AddCategoryView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Category
    template_name = 'blog_app/add_category.html'
    form_class = CategoryForm
    success_message = "Category added!"
    # put all fields from model on the page
    # fields = '__all__'

    # pass categories to view

    def get_context_data(self, *args, **kwargs):
        menu_items = Category.objects.all().values
        context = super(AddCategoryView, self).get_context_data(
            *args, **kwargs)
        context["menu"] = menu_items

        # print(context)
        return context


def FilterView(request, cat):
    filtered_posts = Post.objects.filter(category=cat).all().order_by('-date')
    total = len(filtered_posts.values_list())

    page = request.GET.get('page', 1)

    paginator = Paginator(filtered_posts, 5)

    try:
        filtered_posts = paginator.page(page)
    except PageNotAnInteger:
        filtered_posts = paginator.page(1)
    except EmptyPage:
        filtered_posts = paginator.page(paginator.num_pages)

    context = {
        'category': cat,
        'posts': filtered_posts,
        'total': total
    }

    return render(request, 'blog_app/filtered.html', context)


def FilterAuthorView(request, id):
    filtered_posts = Post.objects.filter(author_id=id).all().order_by('-date')
    total = len(filtered_posts.values_list())

    print(total)
    if total == 0:
        raise Http404("error")

    else:

        page = request.GET.get('page', 1)

        paginator = Paginator(filtered_posts, 5)

        try:
            filtered_posts = paginator.page(page)
        except PageNotAnInteger:
            filtered_posts = paginator.page(1)
        except EmptyPage:
            filtered_posts = paginator.page(paginator.num_pages)

        context = {
            'author': User.objects.get(id=id),
            'posts': filtered_posts,
            'total': total
        }

        return render(request, 'blog_app/filtered_author.html', context)


@login_required
def LikeView(request, pk):
    # get the post to like
    post = get_object_or_404(Post, id=pk)

    # check if logged in user has liked post
    user_liked = post.likes.filter(id=request.user.id)

    if user_liked:
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)

    # return HttpResponseRedirect(reverse('detail', args=[str(pk)]))

    return redirect('detail', post.pk)


@login_required
def CommentView(request, pk):
    post = get_object_or_404(Post, id=pk)

    if request.method == 'POST':
        print(request.POST)

        c = Comment.objects.create(post_id=pk, name=get_current_user(
        ), body=request.POST.get('body'))

        post.comments.add(c)

        return redirect('detail', post.pk)

    context = {
        "form": CommentForm,
        "post": post
    }

    return render(request, 'blog_app/comment.html', context)


class DeleteCommentView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = 'blog_app/delete_comment.html'
    success_message = "Comment deleted!"

    # redirect after a post is deleted
    def get_success_url(self):
        return reverse('home')

    # for success message in delete view we do this -->
    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        messages.success(self.request, self.success_message % obj.__dict__)
        return super(DeleteCommentView, self).delete(request, *args, **kwargs)


def aboutView(request):
    return render(request, 'blog_app/about.html')

blog_app/templates/blog_app/about.html
{% extends 'blog_app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
The Exchange | About 
{% endblock %}

{% block content %}


<div class="m-4 d-flex flex-column align-items-center rounded">
    <img src="{% static 'blog_app/logo.png' %}" alt="" class="logo-big text-center">
    <a href="{% url 'home' %}" class="text-decoration-none text-secondary d-flex justify-content-center align-items-baseline "><b class="title display-4 ">The EXCHANGE</b>
    </a>
    <p class="lead content text-muted p-3 mt-2 text-justify bg-light">A blogging website based on the django web framework, developed as a personal project. The blog features user registeration & authentication, user account editing, post crud, likes & comments. 
    </p>

    <p class="lead content text-muted p-3 m-0 text-justify border-bottom">As this application has been developed by a single person, there might be some bugs & missing features like image uploading. Some features have not been added for developer's convenience as they required a lot more time & tools.
    </p>
    
   
</div>

<div class="d-flex justify-content-sm-center justify-content-around  mb-2 mt-2 ">
    <a href="https://www.linkedin.com/in/krnk97/" class='text-decoration-none  links' target="_blank" ><i class="fab fa-linkedin-in text-info"></i></a>

    <a href="https://github.com/KRNK97" class='text-decoration-none links' target="_blank" ><i class="fab fa-github text-info"></i></a>

    <a href="https://www.instagram.com/_krnk97/" class='text-decoration-none links' target="_blank" ><i class="fab fa-instagram text-info"></i></a>
</div>


{% endblock %}

blog_app/templates/blog_app/add_category.html
{% extends 'blog_app/base.html' %}


{% block title %}
Add new category
{% endblock %}




{% block content %}
{% if user.is_authenticated %}
<h2 class="h5 text-center mt-4 mb-2 py-2 border-info "> <span class="text-muted"></span></h2>


<form method="POST" class="p-4 mt-2">
    {% csrf_token%}

    <div class="form-group">
        {% if form.name.errors %}
        {% for error in form.name.errors %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
        {% endif %}
        <div class="text-info login-form"><b>Name Your Category</b></div>
        <input type="text" name="name" class="form-control inputs" placeholder="enter a name for the new category" required>
    </div>

    <button class="btn btn-outline-info btn-block" type="submit">Add Category</button>
    <button onClick="window.history.back();return false;" class="mt-2 text-decoration-none btn btn-block btn-dark ">Cancel</span></button>

    <div class="small text-muted p-2 my-2">NOTE - Newly created categories don't show up in selection until the app is restarted by the admin.</div>

</form>

<h2 class="h6 text-center mt-4 border-bottom py-2">Currently available categories</h2>

<div class="py-2">
{% for cat in menu %}
    <a class="dropdown-item text-info " href="{% url 'filter' cat.name %}">{{ cat.name|title }}</a>
{% endfor %}
</div>

{% else %}
<div class="display-4 mt-4 alert alert-danger">Login Required</div>
<div class="h4 mt-1">Please login to add categories.</div>

{% endif %}



{% endblock %}

blog_app/templates/blog_app/add_post.html
{% extends 'blog_app/base.html' %}


{% block title %}
Add new post
{% endblock %}




{% block content %}
{% if user.is_authenticated %}
<h2 class="h5 text-center mt-4 mb-2 py-2 border-info "><span class="text-muted inputs">New Post</span></h2>

{{ form.media }}
<form method="POST" class="p-4   mt-2">
    {% csrf_token%}

    <div class="form-group">
        {% if form.title.errors %}
        {% for error in form.title.errors %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
        {% endif %}
        <div class="text-info login-form">
        <b>{{ form.title.label }}</b>
        <input type="text" name="title" class="form-control inputs" placeholder="title of your post " required>
        </div>
    </div>
    <div class="form-group">
        {% if form.content.errors %}
        {% for error in form.content.errors %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
        {% endif %}
        <div class="text-info login-form">
        <b class="d-block">{{ form.content.label }}</b>
        <p class="info text-muted">There is an issue with ckeditor on mobile devices. Text selection isn't possible on mobile. The editor works fine on other devices.
        Also use image width < 270 to avoid sizing problems on phones.
        </p>

        <textarea name="content" id="content" cols="30" rows="10" class="form-control inputs border p-3" placeholder="write your post here" required></textarea>
        </div>
        <!-- {{ form.content }} -->
    </div>
    <div class="form-group">
        {% if form.category.errors %}
        {% for error in form.category.errors %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
        {% endif %}
        <div class="text-info login-form">
        <b><label for="id_category">Category:</label></b>
        {{ form.category }}
        </div>
    </div>

    <div class="form-group">
        {% if form.author.errors %}
        {% for error in form.author.errors %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
        {% endif %}
        <div class="text-info login-form">
        <!-- <b>{{ form.content.label }}</b> -->
        {{ form.author }}
        </div>
    </div>

   


    <button class="btn btn-outline-info btn-block" type="submit">Post</button>
    <button onClick="window.history.back();return false;" class="mt-2 text-decoration-none btn btn-block btn-dark ">Cancel</span></button>
</form>


<!-- set author as the logged in users id -->
<script>

    let id = "{{ user.id }}";
    document.getElementById('authorbox').value = id;

</script>

{% else %}
<div class="d-flex justify-content-between border border shadow mt-4 p-4">
    <div class="">
        <div class="display-4 mt-2 text-danger">ERROR</div>
        <div class="h4 mt-1">You can't access this page.</div>
    </div>

    <div class="mt-2">
        <img src="https://www.flaticon.com/svg/vstatic/svg/1179/1179237.svg?token=exp=1611919698~hmac=345be6f0b33e4ef97d1494c0f07ebc6e" alt="" class="m-auto error_img">
    </div>
</div>


{% endif %}


<script>
    CKEDITOR.replace('content');
    CKEDITOR.config.width="100%";
    CKEDITOR.config.height="400px";
</script>


{% endblock %}

blog_app/templates/blog_app/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}
        {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Roboto:wght@400;500&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'blog_app/main.css' %}">

    <script src="https://kit.fontawesome.com/11b91cfe01.js" crossorigin="anonymous"></script>

    {{ form.media }}

</head>
<body>

    <nav class="navbar bg-light p-3 shadow-sm navbar-custom">
        <nav class="nav-item">
            <div class="h4 d-inline">
                <a href="{% url 'home' %}" class="text-decoration-none text-dark"><b class="title-main text-center">The EXCHANGE</b>
                    <!-- <img src="{% static 'blog_app/logo.png' %}" alt="" class="logo2 "> -->
                </a>
            </div>
            

        <div class="border rounded d-flex justify-content-center align-items-center p-1 shadow-sm">

            <a href="{% url 'about' %}" class="text-decoration-none text-info   navbar-links mx-2"><span class=""><b>About</b></span></a>

            {% if menu %}
            <div class="dropdown d-inline  navbar-links">
                <a class="text-decoration-none dropdown-toggle text-info navbar-links" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="h6 text-info navbar-links"><b>Categories</b></span>
                </a>
              
                <div class="dropdown-menu navbar-links" aria-labelledby="dropdownMenuLink">
                    {% for cat in menu %}
                    <a class="dropdown-item text-info" href="{% url 'filter' cat.name %}">{{ cat.name }}</a>
                    {% endfor %}
                </div>
            </div>
            {% else %}
            <a href="{% url 'home' %}" class="text-decoration-none text-info   navbar-links mx-1"><span class=""></span><b>Home</b></a>
            {% endif %}

            {% if user.is_authenticated %}
            
                <a href="{% url 'add_category' %}" class="text-decoration-none text-info navbar-links d-flex justify-self-center mx-2">
                <b>+ Category</b></a>
           
                {% endif %}
        </div>
            


           

        </nav>
        
        
        

        <nav class="nav-item d-flex justify-content-center mt-md-0 mt-1">
            {% if user.is_authenticated %}
            <a href="{% url 'add_post' %}" class="text-decoration-none text-info  navbar-links"><span class=""><i class="fas fa-pencil-alt"></i></span> <b>Post</b></a>
            <a href="{% url 'account' user.pk %}" class="text-decoration-none text-info  ml-2 navbar-links"><span class=""><i class="fas fa-user"></i></span> <b>{{ user.username }}</b></a>
            <!-- logout will automatically be django logout view and will use home as redirect, no html page (members/logout) -->
            <a href="{% url 'logout' %}" class="text-decoration-none text-info  ml-2 navbar-links"><span class=""><i class="fas fa-sign-out-alt"></i></span> <b>Logout</b></a>
            {% else %}
            <!-- login & reg url will be automatically django views (members/login), it will use a template from members app -->
            <a href="{% url 'login' %}" class="text-decoration-none text-info  navbar-links "><span class=""><i class="fas fa-sign-in-alt"></i></span> <b>Login</b></a>
            <a href="{% url 'register' %}" class="text-decoration-none text-info  ml-2 navbar-links "><span class=""><i class="fas fa-user-plus"></i></span> <b>Register</b></a>
            {% endif %}
        </nav>


       
        
    </nav>
    {% if messages %}
    {% for message in messages %}
        <div class="text-center alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}

    <div class="container-sm">
        
        {% block content %}
        {% endblock %}
    </div>


    

    <script src="{% static 'blog_app/app.js '%}"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

blog_app/templates/blog_app/comment.html
{% extends 'blog_app/base.html' %}

{% block title %}
Add comment
{% endblock %}


{% block content %}

{% if user.is_authenticated %}
<h2 class="h5 text-center mt-4 mb-2 py-2 border-info text-muted"></h2>
    
    <div class="d-flex justify-content-between">
        <div class="text-muted small"></div>
        <div class="text-info title">{{ post.title }}</div>
    </div>
    <div class="d-flex justify-content-between">
        <div class="text-muted small">Posting comment</div>
        <div class="small text-muted">by {{ post.author }}</div>
    </div>
    
   


<form method="POST" class="p-0 mt-2 ">
    {% csrf_token%}

    <div class="form-group border">
        {% if form.body.errors %}
        {% for error in form.body.errors %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
        {% endif %}
        <div class="text-info login-form">
        <textarea name="body" id="body" cols="30" rows="10" class="form-control inputs p-3 rounded shadow-sm" placeholder="write your comment here" required></textarea>
        </div>
    </div>

    <button class="btn btn-outline-info btn-block" type="submit">Post Comment</button>
    <button onClick="window.history.back();return false;" class="mt-2 text-decoration-none btn btn-block btn-dark ">Cancel</span></button>
</form>


{% else %}
<div class="d-flex justify-content-between border border shadow mt-4 p-4">
    <div class="">
        <div class="display-4 mt-2 text-danger">ERROR</div>
        <div class="h4 mt-1">You can't access this page.</div>
    </div>

    <div class="mt-2">
        <img src="https://www.flaticon.com/svg/vstatic/svg/1179/1179237.svg?token=exp=1611919698~hmac=345be6f0b33e4ef97d1494c0f07ebc6e" alt="" class="m-auto error_img">
    </div>
</div>


{% endif %}

{% endblock %}

blog_app/templates/blog_app/update_post.html
{% extends 'blog_app/base.html' %}


{% block title %}
Add new post
{% endblock %}




{% block content %}
{% if post.author.username == user.username %}
<h2 class="h5 text-center mt-4 mb-2 py-2  "> <span class="text-muted">Edit Post</span></h2>


<form method="POST" class="p-4  mb-4">
    {% csrf_token%}
    <span class="">Post </span><div class="h5 mb-4  p-2 bg-light rounded"> {{ post.title }}</div>

    <div class="form-group">
        {% if form.title.errors %}
        {% for error in form.title.errors %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
        {% endif %}
        <div class="text-info login-form">
        <b>{{ form.title.label }}</b>
        <input type="text" name="title" class="form-control inputs" placeholder="Title of your Post" required value="{{ form.title.value }}">
        </div>
    </div>

    <div class="form-group">
        {% if form.content.errors %}
        {% for error in form.content.errors %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
        {% endif %}
        <div class="text-info login-form">
        <b class="d-block">{{ form.content.label }}</b>
        <p class="info text-muted">There is an issue with ckeditor on mobile devices. Text selection isn't possible on mobile. The editor works fine on other devices.
        Also use image width < 270 to avoid sizing problems on phones.
        </p>

        <textarea name="content" id="content" cols="30" rows="10" class="form-control inputs border p-3 richtext " placeholder="update post" required>{{form.content.value}}</textarea>
        <!-- {{ form.content }} -->
        </div>
    </div>

    <div class="form-group">
        {% if form.category.errors %}
        {% for error in form.category.errors %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
        {% endif %}
        <div class="text-info login-form">
        <b><label for="id_category">Category:</label></b>
        {{ form.category }}
        </div>
    </div>

    <div class="form-group">
        {% if form.author.errors %}
        {% for error in form.author.errors %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
        {% endif %}
        <div class="text-info login-form">
        <!-- <b>{{ form.content.label }}</b> -->
        {{ form.author }}
        </div>
    </div>

    <button class="btn btn-outline-info btn-block" type="submit">Edit</button>
    <button onClick="window.history.back();return false;" class="mt-2 text-decoration-none btn btn-block btn-dark ">Cancel</span></button>
</form>

{% else %}
<div class="d-flex justify-content-between border border shadow mt-4 p-4">
    <div class="">
        <div class="display-4 mt-2 text-danger">ERROR</div>
        <div class="h4 mt-1">You can't access this page.</div>
    </div>

    <div class="mt-2">
        <img src="https://www.flaticon.com/svg/vstatic/svg/1179/1179237.svg?token=exp=1611919698~hmac=345be6f0b33e4ef97d1494c0f07ebc6e" alt="" class="m-auto error_img">
    </div>
</div>

{% endif %}
<script>
    CKEDITOR.replace('content');
    CKEDITOR.config.width="100%";
    CKEDITOR.config.height="400px"
</script>

{% endblock %}